# Generated by Django 5.0.3 on 2024-03-26 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_delete_upscale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upscale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upscale', models.ImageField(upload_to='upscale/')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.image')),
            ],
        ),
    ]
