# Generated by Django 5.0.3 on 2024-03-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_upscale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upscale',
        ),
    ]
