# Generated by Django 5.0.3 on 2024-03-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_removedbg'),
    ]

    operations = [
        migrations.AddField(
            model_name='removedbg',
            name='original',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
